var fakeData =
    [
        {id: 101, instructor: 'Nayeem Hasan', name: 'HTML full course', price: 2000, img: 'https://i.ibb.co/w4ty9sc/html.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 102, instructor: 'Tahmid Rafi', name: 'Javascript full course', price: 5000, img: 'https://i.ibb.co/RHvzhQv/js.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 103, instructor: 'Jhankar Mahbub', name: 'Bootstrap full course', price: 2000, img: 'https://i.ibb.co/vLc23Vf/bootstrap.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 104, instructor: 'Tahmid Rafi', name: 'Angular JS full course', price: 5000, img: 'https://i.ibb.co/M1mTvtr/angular.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 105, instructor: 'Tamim Sahriar', name: 'C++ full course', price: 5000, img: 'https://i.ibb.co/VYPn4wT/cpp.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 106, instructor: 'Mafinar Khan', name: 'Django full course', price: 3000, img: 'https://i.ibb.co/CPLGFk1/django.webp', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 107, instructor: 'Buzlor Rahman', name: 'Java full course', price: 5000, img: 'https://i.ibb.co/c8g97b3/java.webp', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 108, instructor: 'Manik Roy', name: 'Mongo DB full course', price: 2500, img: 'https://i.ibb.co/mXLbWNb/mongo.webp', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 109, instructor: 'Rasel Ahmed', name: 'Mysql full course', price: 4500, img: 'https://i.ibb.co/q9Fmwt0/mysql.jpg', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 110, instructor: 'Milon', name: 'Node JS full course', price: 4500, img: 'https://i.ibb.co/825bRP0/node.jpg', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 111, instructor: 'Hasin Hayder', name: 'PHP full course', price: 7000, img: 'https://i.ibb.co/fCDjGGM/php.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 112, instructor: 'Maksudur Rahman', name: 'Python full course', price: 60000, img: 'https://i.ibb.co/YNB5B7h/python.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 113, instructor: 'Jhankar Mahbub', name: 'React JS full course', price: 4000, img: 'https://i.ibb.co/Wn9WW4F/react.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 114, instructor: 'Mizanur Rahman', name: 'Vue JS full course', price: 3000, img: 'https://i.ibb.co/N9vcdWy/vue.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 115, instructor: 'Niloy', name: 'CSS full course', price: 2000, img: 'https://i.ibb.co/cLkv6S2/css.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 

    ];

export default fakeData;